version: '3.6'
services:
  iris:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 51779:1972
      - 52779:52773
      - 53779:53773
    volumes:
      - ./:/home/irisowner/dev
